### ISSUE TITLE
Crash iterating types of inodes

### ISSUE THREAD

**Issue by xloem** [fox-it/dissect.squashfs#11]
I ended up finding other tools rather than pursuing these failures further.

```
  File "/usr/lib/python3.9/site-packages/dissect/squashfs/squashfs.py", line 272, in is_file
    return self.type == stat.S_IFREG
  File "/usr/lib/python3.9/site-packages/dissect/squashfs/squashfs.py", line 239, in type
    return TYPE_MAP[self._type or self.header.inode_type]
  File "/usr/lib/python3.9/functools.py", line 993, in __get__
    val = self.func(instance)
  File "/usr/lib/python3.9/site-packages/dissect/squashfs/squashfs.py", line 225, in header
    if len(actual_struct) != len(base_struct):
TypeError: object of type 'NoneType' has no len()
```
looks like a corrupt header is read
```
(Pdb) p header.inode_type
35848
```

The archive is a public snap, which are in squashfs format: https://api.snapcraft.io/api/v1/snaps/download/XKEcBqPM06H1Z7zGOdG5fbICuf8NWK5R_1862.snap

**Comment by Schamper** [comment]
#12 should fix this, could you share the code snippet that caused this bug or otherwise test if it still crashes with the changes in that PR?

**Comment by xloem** [comment]
I’m afraid I’m not working with this more nor near the code; I recall it walked all inodes in a simple manner (likely retrieving their types) and this caused the crash. I’ll close it. Thanks for addressing these.

**Comment by Schamper** [comment]
I spent a little bit more time on this and it turns out this is a bug in our [native Python LZO implementation](https://github.com/fox-it/dissect.util/blob/main/dissect/util/compression/lzo.py). The issue does not occur when using `python-lzo`.

I'll debug further and fix it there.
